export const FETCH_USER = 'FETCH_USER';

export const CREATE_SURVEY='CREATE_SURVEY';
export const GO_TO_NEXT_PAGE='GO_TO_NEXT_PAGE';
export const GO_TO_PREV_PAGE='GO_TO_PREV_PAGE';
export const FETCH_SURVEY='FETCH_SURVEY';
export const ADD_REPLY ='ADD_REPLY';

export const UPDATE_SURVEY='UPDATE_SURVEY';

export const ADD_QUESTION='ADD_QUESTION';
export const ADD_ANSWER='ADD_ANSWER';
export const REMOVE_QUESTION='REMOVE_QUESTION';
export const REMOVE_ANSWER='REMOVE_ANSWER';

