export const FETCH_USER = 'FETCH_USER';
export const CREATE_SURVEY='CREATE_SURVEY';

export const GO_TO_NEXT_PAGE='GO_TO_NEXT_PAGE';
export const GO_TO_PREV_PAGE='GO_TO_PREV_PAGE';

export const UPDATE_SURVEY='UPDATE_SURVEY';

